version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraftdata3:/data
      - plugins3:/plugins
    ports:
      - ${HOST_PORT:25565}
    environment:
      EULA: "TRUE"
      TYPE: {TYPE}
      VERSION: {VERSION}
      MEMORY: {MEMORY}
      OPS: "Rooiepanda"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      RCON_PORT: ${RCON_PORT:-25574}
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  minecraftdata3:
  plugins3:

